### ISSUE TITLE
Split API logic and CLI commands into different packages

### ISSUE THREAD

**Issue by Crevil** [lokalise/lokalise-cli-go#1]
It's great to have the CLI commands available as Go code.
To make this more available as an SDK for Go applications the API logic should be separated from the CLI. This way Go applications can import the logic parts and facilitate the functions directly.

Basically, `Action` functions should only do the context parsing and then call a function to do the heavy lifting.

If your interested I could provide a PR doing this.

**Comment by nickustinov** [comment]
Certainly, please do. Thank you.
