### ISSUE TITLE
EnsureEscape don't follow option pattern

### ISSUE THREAD

**Issue by Crevil** [lokalise/lokalise-cli-go#10]
I would have expected the newly added `EscapePercent` option creator to be named `WithEscapePercent` (or maybe `WithPercentEscape` to be more readable).
 
https://github.com/lokalise/lokalise-cli-go/commit/adbf44029d54fb7e813352b05cddf452d8725298#diff-446c77923f5c6a627c3f8587428527ddR196

Are there any reasons for it not to follow the pattern of the other option creators?

**Comment by nickustinov** [comment]
My bad, could you fix this and create a PR when convenient.

**Comment by Crevil** [comment]
Sure thing 👍
