### ISSUE TITLE
Intermittent Lokalise API issue

### ISSUE THREAD

**Issue by neilco** [lokalise/lokalise-cli-go#12]
My team is facing an intermittent problem when using the Lokalise CLI tool. Every now & then, we'll see the following error when running the export command:

```shell
unexpected end of JSON input
ERROR: API returned error (see above)
```

I've debugged the CLI tool and I've found that when this error occurs the API is returning a status of 200 with an empty response body and a `Content-Length` header of `-1`. This is causing the JSON deserialiser to fail since `body` is just an empty byte slice (hence the `unexpected end of JSON input` error). This suggests there's an underlying problem upstream in your API and it's resulting in an invalid response.

**Comment by nickustinov** [comment]
Hi Neilco!

We've noticed an issue today, that was related to ReactNative export that could cause such problems in the CLI.

Could you please contact us in the in-web support chat at lokalise.co so we can identify the problem? 

Nick
