### ISSUE TITLE
Options for Import and Export functions

### ISSUE THREAD

**Issue by Crevil** [lokalise/lokalise-cli-go#7]
We've been using the `lokalise` package now for a while and here is the first of a couple of proposed API changes.

The API for `Import` and `Export` functions in the `lokalise` package is cumbersome to use.

The `ImportOptions` and `ExportOptions` structs with pointers to `bool` values requires a bool instance assignment before use, leading to code like this:

```go
t := true
f := false
lokalise.Import("token", "projectID", "file", "en", &lokalise.ImportOptions{
  Replace: &t,
  ReplaceBreaks: &f,
})
```

## Sugested change
For a more Go idiomatic API I suggest changing the structs to a variadic `Option` argument enabling functional options ([Dave Cheney](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis)).
This enables developers to set features in a more fluent way. The above example could become:

```go
lokalise.Import("token", "projectID", "file", "en",
  lokalise.WithReplace(true),
  lokalise.WithReplaceBreaks(false),
)
```

This way the client can specify any number of options and it's possible to extend the functionality by simply adding another `Option`.

A nice thing about this is that it gets a little easier to add explaining documentation to each `Option` as well. See the [Google API options](https://godoc.org/google.golang.org/api/option) for a great example of this.

If the proposed change sounds good to you, are we, as always, ready to hack a PR up implementing it if needed.

**Comment by nickustinov** [comment]
Sounds good, please do! 👍

**Comment by nickustinov** [comment]
I was also thinking about renaming and regrouping some switches (well quite many of them). 

Naturally, we would update the API parameters as well and support old and new ones, so if you could come up with a way of adding aliases to each parameter it would be grea, let's say --type would be --file-format, but --type should work too.

Nick

**Comment by Crevil** [comment]
Sure thing. I'll look into it this week or the next.

**Comment by Crevil** [comment]
I'm just about to submit a PR for this change. I'll just hear your opinion on some client validation.

Does it make sense to you to limit inputs based on option values on the client or should I leave this to the API?

*Pros for limiting inputs client side*
User gets immediate feedback when having a typo, eg. `a-z` instead of `a_z`

*Cons for limiting inputs client side*
Changes to the available values must lead to an update in the libraries.

What do you think is nicest? Do you want the flexibility to change the constraints server side?

**Comment by nickustinov** [comment]
Lets go with client side validation.
